version: '3'

services:
  php_dev:
    build: ./.docker/php_dev
    container_name: ${COMPOSE_PROJECT_NAME}-php-dev
    restart: unless-stopped
#    user: '${HOST_USER_ID}:${HOST_USER_GROUP_ID}'
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
